# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html
# pushd /workspaces/reports/volume/ansible
# ansible-playbook reboot.yml -i inventory.yaml -b --ask-become-pass
---
- name: Basic usage
  hosts: moto
  # hosts: reports3
  # hosts: reports5
  remote_user: brent
  tasks:
  - name: basic usage
    ansible.builtin.debug:
      msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}' is the HOME environment variable."
  - name: Reboot a slow machine that might have lots of updates to apply
    ansible.builtin.reboot:
      reboot_timeout: 3600
